version: '3.3'
services:
  back:
    container_name: "wheater-app-back"
    build:
      context: .
      dockerfile: ./docker/back/Dockerfile
    ports: ["5000:5000"]
  front:
    container_name: "wheater-app-front"
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
    ports: ["8080:8080"]